name: Test

on: 
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8]

    if: github.repository == 'hand10ryo/PytorchCML'

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
          poetry run flake8 --ignore=E501 PytorchCML tests
          poetry run python -m unittest discover -b
